# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: CivicActions
email: contact@civicactions.com
description: Digital services that work for everyone.
baseurl: "/web-prototype" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username: civicactions
twitter_username: civicactions
facebook: https://www.facebook.com/CivicActions
linkedin: https://www.linkedin.com/company/civicactions
rss: news/atom.xml

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

repo: https://github.com/civicactions/civicactions.github.io/
branch: master

feed:
  path: news/atom.xml

permalink: /:title/

collections:
  training:
    output: true
    permalink: training/:title
  case-studies:
    output: true
    permalink: case-studies/:title
  consulting:
    output: true
    permalink: consulting/:title
  people:
    output: true
    permalink: people/:title
  guide:
    output: true
    permalink: guide/:title
  talks:
    output: true
    permalink: talks/:title
  handbook:
    output: true
    permalink: handbook/:title
  coaching:
    output: true
    permalink: coaching/:title
  help:
    output: true
    permalink: help/:title
  pages:
    output: true
    permalink: :title
  topics:
    output: true
    permalink: topics/:title

defaults:
  - scope:
      path: ""
      type: "people"
    values:
      layout: "people"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: news/:title
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"

paginate: 10
paginate_path: "/news/page:num/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - _training/TEMPLATE-training.md
  - _coaching/TEMPLATE-coaching.md
  - _consulting/TEMPLATE-consulting.md
  - _help/TEMPLATE-help.md
  - _people/people-TEMPLATE.md
  - assets
  - Gemfile
  - Gemfile.lock
